#!/usr/bin/env bash

major_version=6

cache_dir=$CM_DIR/clipmenu.$major_version.$USER
cache_file=$cache_dir/line_cache

list_clips() {
    LC_ALL=C sort -rnk 1 < "$cache_file" | cut -d' ' -f2- | awk '!seen[$0]++'
}

if [[ $1 ]]; then
    clipdel -d "$1"
fi
list_clips

