alias ..='cd ..'
alias ...='cd ../..'
alias ls='exa'
alias la='exa -la'
alias ll='exa -lh'
alias lt='exa --tree'
alias cat='bat'
alias grep='rg'
alias cal='cal -3'
alias diff='diff --color=always'
alias grep='grep --color=always'
alias print='figlet'
alias count='find . -type f | wc -l'
alias clock='tty-clock -c'
alias term='xfce4-terminal'
alias pipes='pipes.sh'
alias intop='sudo intel_gpu_top'
alias awconf='micro ~/.config/awesome/rc.lua'
alias piconf='micro ~/.config/picom/picom.conf'
alias upsearch='sudo updatedb -U "$HOME" -e "$HOME/.config" -e "$HOME/.local" -e "$HOME/.cache"'
alias transmission='transmission-daemon && tremc'
alias ps='pamac search'
alias pi='pamac install'
alias pc='pamac checkupdates'
alias pd='pamac info'
alias pr='pamac remove'
alias pu='pamac update'
