notify = true
use_nerdfont = true

library_tabs = ["tracks", "playlists", "browse", "artists", "albums", "podcasts"]

[keybindings]
# Views
"1" = "focus library"
"2" = "focus queue"
"3" = "focus search"
"f" = "focus search"

# Navigation
"Enter" = "play"
"Backspace" = "back"
"q" = "back"
"Home" = "move top"
"End" = "move bottom"
"Up" = "move up 1"
"Down" = "move down 1"
"Left" = "move left 1"
"Right" = "move right 1"
"PageUp" = "move up 5"
"PageDown" = "move down 10"

# Fast forward / rewind
"[" = "seek -3s"
"]" = "seek +5s"
"{" = "seek -10s"
"}" = "seek +10s"

# Volume
"=" = "volup 5"
"-" = "voldown 5"

# Track manipulation
"c" = "playpause"
"z" = "previous"
"x" = "next"
"r" = "repeat"
"s" = "shuffle"
"S" = "save"
"D" = "delete"

# Open context menu
"w" = "open selected"
"Shift+w" = "open current"
"a" = "goto artist"
"Shift+a" = "goto album"
"p" = "similar current"
"Ctrl+p" = "similar selected"

# Queue
# Add to queue
"e" = "queue"
"Ctrl+s" = "save queue"
# Move selected song up/down in the queue
"Shift+z" = "shift up 1"
"Shift+x" = "shift down 1"
"," = "shift up 1"
"." = "shift down 1"
"<" = "shift up 5"
">" = "shift down 5"
"Ctrl+l" = "clear"
# Open the context menu for a Spotify link in the clipboard
"Ctrl+v" = "insert"

# Sorting
"t" = "sort added d"
"Shift+t" = "sort title a"

# Sharing
"Shift+y" = "share selected"
"y" = "share current"

# Other
"Shift+q" = "quit"
"?" = "help"
"Shift+u" = "update"

[notification_format]
title = "%title"
body = "%artists - %album"

[theme] 
# Spotify
# background = "black"
primary = "white"
secondary = "light white"
title = "green"
playing = "green"
playing_selected = "light green"
playing_bg = "black"
highlight = "light white"
highlight_bg = "light black"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "light white"
cmdline_bg = "black"
search_match = "light red"
